---
- name: install apache web server (http)
  yum:
   name: httpd
   state: latest
- name: start apache
  service:
    name: httpd
    state: started
- name: copy index.html file
  copy:
    src: index.html
    dest: /var/www/html

